### ISSUE TITLE
Não estou conseguindo usar, pode me ajudar?

### ISSUE THREAD

**Issue by jonasaraujo96** [djalmaoliveira/djf-danfe#1]
Bom dia, eu coloquei o xml na variavel e gerou a danfe quando eu executei o comando "npm run test", funcionou perfeitamente, mas eu gostaria de usar isso na minha aplicação feita em Ionic, como eu posso gerar sem colocar um comando no terminal?

**Comment by djalmaoliveira** [comment]
[Use esse código de teste como base para sua aplicação](https://github.com/djalmaoliveira/djf-danfe/blob/master/test/index.js#L9-L41), ele gera um arquivo HTML no qual você pode visualizar em um navegador.
